site_name: Cognix
docs_dir: "src"
site_url: "https://datakami.github.io/cognix"
site_dir: !ENV out

repo_url: https://github.com/datakami/cognix
repo_name: datakami/cognix
edit_uri: edit/main/website/src/

plugins:
  - search
  - awesome-pages

hooks:
  - render_options.py

extra_css:
  - style.css

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.escapeall
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.details

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  custom_dir: d2n/theme
  name: material
  # favicon: favicon.png
  # logo: favicon.png
  features:
    - search.suggest
    - search.highlight
    - instant
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datakami/cognix
      name: Cognix on Github
