name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a56e3a80896f10bfe28feea2c49695c0225b2485
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          echo "before rm"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "before build"
          df -h
          nix flake check --allow-import-from-derivation --keep-failed || df -h
