name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a56e3a80896f10bfe28feea2c49695c0225b2485
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          echo "building"
          # remove some useless paths, saves 10GB
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          nix flake check --allow-import-from-derivation
